name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_express_pdf_generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image for express PDF generator
        uses: docker/build-push-action@v2
        with:
          # context: ./dash-app
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build_express_pdf_generator]

  #   steps:
  #     - name: Execute SSH command
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USER }}
  #         key: ${{ secrets.VPS_SSH_KEY }}
  #         script: |
  #           cd /path/to/your/scripts
  #           ./update-docker.sh